app:
  scheduler:
    interval: 1000
  database-access-type: jdbc
  queue: rabbitQ
  exchange: rabbitEx
  bind: scrapper
  use-queue: true
server:
  port: 8180
spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password
  liquibase:
    change-log: classpath:migrations/master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
springdoc:
  swagger-ui:
    path: /swagger-ui.html
github:
  base-url: https://api.github.com
stackoverflow:
  base-url: https://api.stackexchange.com/2.3
bot:
  base-url: http://localhost:8080
