app:
  scheduler:
    interval: 10000
  database-access-type: jpa
  queue: rabbitQ
  exchange: rabbitEx
  bind: scrapper
  use-queue: false
server:
  port: 9000
spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password
  liquibase:
    change-log: classpath:migrations/master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
springdoc:
  swagger-ui:
    path: /swagger-ui.html
github:
  base-url: https://api.github.com
stackoverflow:
  base-url: https://api.stackexchange.com/2.3
bot:
  base-url: http://localhost:8000
management:
  server:
    port: 9001
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - info
          - health
          - prometheus
      path-mapping:
        prometheus: metrics
    enabled-by-default: true
  metrics:
    tags:
      app: 'scrapper'