# This is a basic workflow to help you get started with Actions

name: Bot CI

# Controls when the workflow will run
on:
  push:
    paths:
      - 'StackHub/bot/**'
      - '.github/**'
      - 'StackHub/checkstyle.xml'

env: # lookup key as an environment variable
  token: ${{ secrets.TOKEN }}
  name: ${{ secrets.NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: StackHub
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven build
        run: mvn -Dtoken=${{ env.token }} -Dname=${{ env.name }} package -pl bot -am  

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --file ./bot/Dockerfile -t ghcr.io/${{github.actor}}/stackhub-bot:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{github.actor}}/stackhub-bot:latest

  checkstyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StackHub
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run check style
        run: mvn -pl bot -am checkstyle:check
